import { INodeTypeDescription } from 'n8n-workflow';

export const maxBotTriggerPollingDescription: INodeTypeDescription = {
  displayName: 'MAX Bot Trigger Polling',
  name: 'maxBotTriggerPolling',
  icon: 'file:max.svg',
  group: ['trigger'],
  version: 1,
  description: 'Receive events from MAX Bot via long polling (no external access needed)',
  defaults: { name: 'MAX Bot Trigger Polling' },
  inputs: [],
  outputs: ['main'],
  credentials: [{ name: 'maxBotApi', required: true }],
  polling: true,
  properties: [
    {
      displayName: 'Events',
      name: 'events',
      type: 'multiOptions',
      required: true,
      default: ['message_created'],
      description: 'Events to listen for',
      options: [
        { name: 'Message Created', value: 'message_created', description: 'New message in chat' },
        { name: 'Message Callback', value: 'message_callback', description: 'Callback button pressed' },
        { name: 'Message Edited', value: 'message_edited', description: 'Message edited' },
        { name: 'Message Removed', value: 'message_removed', description: 'Message removed' },
        { name: 'Bot Started', value: 'bot_started', description: 'Dialog started with bot' },
        { name: 'Bot Added', value: 'bot_added', description: 'Bot added to chat' },
        { name: 'Bot Removed', value: 'bot_removed', description: 'Bot removed from chat' },
        { name: 'User Added', value: 'user_added', description: 'User added to chat' },
        { name: 'User Removed', value: 'user_removed', description: 'User removed from chat' },
        { name: 'Chat Title Changed', value: 'chat_title_changed', description: 'Chat title changed' },
        { name: 'Message Construction Request', value: 'message_construction_request', description: 'Message construction request' },
        { name: 'Message Constructed', value: 'message_constructed', description: 'Message constructed' },
        { name: 'Message Chat Created', value: 'message_chat_created', description: 'Chat created via button' },
      ],
    },
    {
      displayName: 'Poll Interval',
      name: 'pollInterval',
      type: 'number',
      default: 15,
      required: true,
      description: 'Interval in seconds between polls (minimum 5s)',
    },
    {
      displayName: 'Limit',
      name: 'limit',
      type: 'number',
      default: 10,
      required: false,
      description: 'Max number of updates per poll',
    },
  ],
};
